--- #YAML:1.0
name:               DBIx-QueryByName
version:            0.13
abstract:           Execute SQL queries by name
author:
    - Joel Jacobson <joel@gluefinance.com, Erwan Lemonnier <erwan@gluefinance.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    accessors::chained:  1.01
    XML::Parser:         2.34
    XML::SimpleObject:   0.53
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
