# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-QueryByName
version:      0.07
version_from: lib/DBIx/QueryByName.pm
installdirs:  site
requires:
    accessors::chained:            1.01
    XML::Parser:                   2.34
    XML::SimpleObject:             0.53

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
